---
- name: Check if Helm binary exists.
  ansible.builtin.stat:
    path: "{{ helm_bin_path }}"
  register: helm_check

- name: Check Helm version.
  ansible.builtin.command: "{{ helm_bin_path }} version"
  failed_when: false
  changed_when: false
  register: helm_existing_version

- name: Download helm.
  ansible.builtin.unarchive:
    src: "{{ helm_repo_path }}/helm-{{ helm_version }}-{{ helm_platform }}-{{ helm_arch }}.tar.gz"
    dest: /tmp
    remote_src: true
    mode: 0755
  register: helm_download
  notify: Copy helm binary into place.
  when: >
    not helm_check.stat.exists
    or helm_version not in helm_existing_version.stdout
